version: "3.8"

services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=fullstack
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks: 
      - local

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      - local

  api:
    container_name: api
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:12345@postgres_container:5432/fullstack
    depends_on:
      - db
      - minio
    volumes:
      - ./apps/server:/app
      - /app/node_modules
    networks: 
      - local

  client:
    container_name: client
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - api
    volumes:
      - ./apps/client:/frontend
      - /frontend/node_modules
    networks: 
      - local
  
  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-data:/data
    networks: 
      - local
    
volumes:
  minio-data:
  pgdata:

networks:
  local:
    driver: bridge
