import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../styles';
import { AppProvider } from '../providers/app-provider';
import { Sidebar } from '@/widgets/sidebar';
import { Toaster } from 'react-hot-toast';
import { toastOptions } from '@/shared/config/toaster.config';

const geistSans = localFont({
    src: '../fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: '../fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AppProvider>
            <html lang="en">
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}>
                    <Sidebar />
                    {children}
                    <Toaster position="top-right" toastOptions={toastOptions} />
                </body>
            </html>
        </AppProvider>
    );
}
