import { Metadata } from 'next';
import { Manrope } from "next/font/google";
import '../styles';
import { Toaster } from 'react-hot-toast';
import { AppProvider } from '../providers/app-provider';
import { toastOptions } from '@/shared/config/toaster.config';
import { Sidebar } from '@/widgets/sidebar';

const manrope = Manrope({
    subsets: ["latin"],
    weight: ["200", "400", "500", "700", "800"],
    display: "swap",
    variable: "--font-manrope",
  });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AppProvider>
            <html lang="en">
                <body className={`${manrope.variable} ${manrope.className} antialiased flex`}>
                    <Sidebar />
                    {children}
                    <Toaster position="top-right" toastOptions={toastOptions} />
                </body>
            </html>
        </AppProvider>
    );
}
