name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "18.17.1"

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm install

      - name: Install dependencies
        run: pnpm install

      - name: Navigate to the server directory
        run: cd apps/server

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Linting
        run: pnpm run lint

      - name: Build production project
        run: pnpm run build